1.0
DK-ITM-PP/PP_1.1.4 pull request #1
Opened 2023-07-28 13:01 UTC by DiKiYi

2023-07-29 10:05 UTC, pdasilem requested changes

2023-07-29 10:05 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        try (Session session = sessionFactory.openSession()){
зачем вложенные трай кэтч? избавься

2023-07-30 11:16 UTC, closed without merging

2023-07-30 12:57 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +            Session session = sessionFactory.openSession();
ну а сессию-то закрыть в конце метода?

2023-07-30 12:57 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +    public void myTest() {
это здесь надо?

2023-07-30 13:08 UTC, DiKiYi commented
сессии закрываются, в MyTest как раз отслеживается состояние сессий.
И я сделал новый пул-реквест
https://github.com/DK-ITM-PP/PP_1.1.4/pull/2

2023-07-30 15:33 UTC, DiKiYi commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +    public void myTest() {
сессии закрываются автоматически при завершении транзакции, а в MyTest как раз можно отследить состояние сессии.
И я сделал новый пул-реквест
https://github.com/DK-ITM-PP/PP_1.1.4/pull/2